name: notesimple
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  animated_icon_button: ^1.0.2
  dismissible_page: ^1.0.2
  flutter:
    sdk: flutter
  flutter_icon_snackbar: ^1.1.4
  flutter_markdown: ^0.6.4
  flutter_quill: ^7.2.6
  flutter_svg: ^2.0.6
  intl: ^0.18.1
  path_provider: ^2.0.15
  sqflite: ^2.2.8+4
  flutter_gif: ^0.0.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/writing.svg
    - assets/images/notfound.svg

  fonts:
    - family: Sarabun
      fonts:
        - asset: assets/fonts/sarabun/Sarabun-Regular.ttf
    - family: lufga
      fonts:
        - asset: assets/fonts/lufga/lufga-regular.otf